branches:
  only:
    - master
env:
  global:
    - TERM=dumb
matrix:
    include:
    - os: osx
      env:
        - BuildiOS="12.1"
        - Xcode="10.1"
      osx_image: xcode10.1
script:
    - sudo rm -rf /usr/local/Caskroom/*
    - sudo rm -rf /usr/local/share/android-sdk
    - sudo rm -rf /Library/Java/JavaVirtualMachines/*
    - ./java/install-java.sh
    - ./java/install-maven.sh
    - ./node/install-node.sh
    - ./appium/install-appium.sh
    - ./android/install-android-sdk.sh
    - ./android/update-android-sdk.sh
    - ./android/update-android-emulators.sh
    - ./tns/install-nativescript.sh
    - tns doctor
